// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID
	FirstName    sql.NullString
	LastName     sql.NullString
	EmailAddress string
	Password     string
	UserActive   sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
